server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    charset iso-8859-1;
    server_tokens off;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~* \.(?:css|js|gif|jpe?g|png|webp|ico)$ {
        expires 30d;
        add_header Cache-Control "public";
        try_files $uri =404;
    }
}
